In [1]:
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])

In [9]:
# Task 1: Merge above two numpy arrays using np.hstack
merged = np.hstack((employee_details,performance_metrics))

In [10]:
performance_metrics

array([[101,  85,   5],
       [102,  78,   3],
       [103,  92,   7],
       [104,  88,   6],
       [105,  79,   4],
       [106,  81,   5],
       [107,  91,   8],
       [108,  77,   4],
       [109,  83,   4]])

In [11]:
employee_details

array([['101', 'Sales', '55000', 'Satya Nadella'],
       ['102', 'HR', '52000', 'Emily Johnson'],
       ['103', 'IT', '72000', 'Fatima Razaak'],
       ['104', 'Sales', '60000', 'John Smith'],
       ['105', 'IT', '68000', 'Priya Singh'],
       ['106', 'HR', '54000', 'Li Wei'],
       ['107', 'IT', '71000', 'Michael Brown'],
       ['108', 'Sales', '59000', 'Sunita Sharma'],
       ['109', 'HR', '53000', 'Chen Wei']], dtype='<U13')

In [12]:
merged

array([['101', 'Sales', '55000', 'Satya Nadella', '101', '85', '5'],
       ['102', 'HR', '52000', 'Emily Johnson', '102', '78', '3'],
       ['103', 'IT', '72000', 'Fatima Razaak', '103', '92', '7'],
       ['104', 'Sales', '60000', 'John Smith', '104', '88', '6'],
       ['105', 'IT', '68000', 'Priya Singh', '105', '79', '4'],
       ['106', 'HR', '54000', 'Li Wei', '106', '81', '5'],
       ['107', 'IT', '71000', 'Michael Brown', '107', '91', '8'],
       ['108', 'Sales', '59000', 'Sunita Sharma', '108', '77', '4'],
       ['109', 'HR', '53000', 'Chen Wei', '109', '83', '4']], dtype='<U13')

In [13]:
# Task 2: Print All the Salaries
merged[:,2]

array(['55000', '52000', '72000', '60000', '68000', '54000', '71000',
       '59000', '53000'], dtype='<U13')

In [14]:
# Task 3: Print All the Salaries in Ascending Order
np.sort(merged[:,2])

array(['52000', '53000', '54000', '55000', '59000', '60000', '68000',
       '71000', '72000'], dtype='<U13')

In [17]:
# Task 4: Iterate through the entire array and print only the employee ID and name
for row in merged:
    print(f'id: {row[0]}, Name: {row[3]}')

id: 101, Name: Satya Nadella
id: 102, Name: Emily Johnson
id: 103, Name: Fatima Razaak
id: 104, Name: John Smith
id: 105, Name: Priya Singh
id: 106, Name: Li Wei
id: 107, Name: Michael Brown
id: 108, Name: Sunita Sharma
id: 109, Name: Chen Wei


In [18]:
# Task 5: Print the performance score of all the employees
merged[:,5]

array(['85', '78', '92', '88', '79', '81', '91', '77', '83'], dtype='<U13')

In [19]:
# Task 6: Convert these scores to float type by using astype(float) function
merged[:,5].astype(float)

array([85., 78., 92., 88., 79., 81., 91., 77., 83.])

In [26]:
# Task 7: Now print the average performance score of all the employees'
np.mean(merged[:,5].astype(float))

83.77777777777777

In [27]:
# Task 8: Print all the unique departments. You can use np.unique function for this
merged[:,1]

array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U13')

In [28]:
np.unique(merged[:,1])

array(['HR', 'IT', 'Sales'], dtype='<U13')

In [29]:
# Task 9: Print the average salary in the HR department
merged[merged[:,1]=='HR']


array([['102', 'HR', '52000', 'Emily Johnson', '102', '78', '3'],
       ['106', 'HR', '54000', 'Li Wei', '106', '81', '5'],
       ['109', 'HR', '53000', 'Chen Wei', '109', '83', '4']], dtype='<U13')

In [30]:
merged[merged[:,1]=='HR'][:,2].astype(float)

array([52000., 54000., 53000.])

In [31]:
np.average(merged[merged[:,1]=='HR'][:,2].astype(float))

53000.0